# Generated by Django 4.1.1 on 2022-11-16 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_post', '0006_remove_codepost_user_codepost_author'),
        ('answers', '0004_alter_answers_answers_alter_answers_answersofuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answersOfUser',
        ),
        migrations.AddField(
            model_name='answers',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authoredPostComments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='post',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='postComments', to='code_post.codepost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answers',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='textContent',
            field=models.TextField(blank=True),
        ),
    ]
