# Generated by Django 4.1.1 on 2022-11-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_email_alter_registration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
