# Generated by Django 4.1.1 on 2022-11-10 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0003_rename_price_badge_cost_rename_name_badge_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Badger', 'Badger'), ('404-error', '404-error')], max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('badges', models.ManyToManyField(blank=True, related_name='wallet', to='badges.badge')),
                ('user', models.ManyToManyField(blank=True, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
