# Generated by Django 4.1.1 on 2022-11-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
        ('general_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlerPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('badges', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handler_posts', to='badges.badge')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handler', to='general_posts.generalposts')),
            ],
        ),
    ]
