# Generated by Django 4.1.1 on 2022-11-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_junior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='junior',
        ),
    ]
