# Generated by Django 4.1.1 on 2022-11-14 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.ManyToManyField(blank=True, related_name='friend_request_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='request',
            field=models.ManyToManyField(blank=True, related_name='friend_request_requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
