# Generated by Django 4.1.1 on 2022-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=250)),
                ('difficulty', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('code', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
