# Generated by Django 4.1.1 on 2022-11-17 09:16

import code_post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(blank=True, choices=[('python', 'python'), ('javascript', 'javascript')], max_length=250)),
                ('difficulty', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('code', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=code_post.models.code_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
