# Generated by Django 4.1.1 on 2022-11-17 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codePosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
