# Generated by Django 4.1.1 on 2022-11-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_post', '0003_alter_codepost_code_alter_codepost_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepost',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'Javascript')], max_length=250),
        ),
    ]
