# Generated by Django 4.1.1 on 2022-11-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_post', '0004_alter_codepost_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepost',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'python'), ('javascript', 'javascript')], max_length=250),
        ),
    ]
