# Generated by Django 4.1.1 on 2022-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_post', '0006_remove_codepost_user_codepost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepost',
            name='difficulty',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
