# Generated by Django 4.1.1 on 2022-11-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
        ('code_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('badges', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='handler_code', to='badges.badge')),
                ('code_posts', models.ManyToManyField(blank=True, related_name='handler', to='code_post.codepost')),
            ],
        ),
    ]
