# Generated by Django 4.1.1 on 2022-11-08 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0003_rename_amount_badge_price_remove_badge_owned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlerUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('badges', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handler_users', to='badges.badge')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
