# Generated by Django 4.1.1 on 2022-11-08 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handler_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='handlerusers',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handler', to=settings.AUTH_USER_MODEL),
        ),
    ]
