# Generated by Django 4.1.1 on 2022-11-09 11:15

import badges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to=badges.models.badge_image_directory_path)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
