# Generated by Django 4.1.1 on 2022-11-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_badge_owned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='owned',
        ),
    ]
