# Generated by Django 4.1.1 on 2022-11-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_badge_answers_badges_badge_code_badges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='answers_badges',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='code_badges',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='comments_badges',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='posts_badges',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='user_badges',
        ),
        migrations.AddField(
            model_name='badge',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
