# Generated by Django 4.1.1 on 2022-11-11 15:16

from django.db import migrations, models
import post_wallet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_posts', '0001_initial'),
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Badger', 'Badger'), ('404-error', '404-error')], max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to=post_wallet.models.badge_image_directory_path)),
                ('badges', models.ManyToManyField(related_name='post_wallet', to='badges.badge')),
                ('post', models.ManyToManyField(related_name='wallet', to='general_posts.generalposts')),
            ],
        ),
    ]
