# Generated by Django 4.1.1 on 2022-11-14 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_post', '0005_alter_codepost_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='code_post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answersToComments', to='code_post.codepost'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
